package fr.lediamantrouge.howermclobby.gui;


import fr.kotlini.supragui.bases.SingleGUI;
import fr.lediamantrouge.howermclobby.util.itembuilder.CreateSkull;
import fr.lediamantrouge.howermclobby.util.itembuilder.ItemBuilder;
import org.bukkit.DyeColor;
import org.bukkit.Material;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.Player;

import java.util.Arrays;

public class MainGUI extends SingleGUI {

    public MainGUI(Player player) {
        super(player.getUniqueId(), "§f▪ §6Menu Principal", 6 * 9);
    }

    @Override
    public void putItems() {
        setItems(getCorners(), new ItemBuilder(Material.STAINED_GLASS_PANE).setWoolColor(DyeColor.RED).setDisplayName(" ").build(false), e -> {});
        setItem(23, new ItemBuilder(new CreateSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTZkN2ZkYjUwZjE0YzczMWM3MjdiMGUwZDE4OWI2YTg3NDMxOWZjMGQ3OWM4YTA5OWFjZmM3N2M3YjJkOTE5NiJ9fX0=").toItemStack()).setDisplayName("              §f▪ §a§lPVPBOX §f▪").addEnchant(Enchantment.KNOCKBACK, 1).setLoreWithList(Arrays.asList("§f§m--§7»§f§m-----------------§7«§f§m--", "  §c§nRègle du jeu §8§l»", "  §7● §fChoisissez un kit, et", "     §fpartez combattre dans", "     §fune grande arène, pour", "     §fatteindre le top du", "     §fclassement.", "", "§f➠ §7Développeur: §60hEliott", "§f➠ §7Version: §a1.8.8", "", "§f➠ §7Booster: Aucun", "§f➠ §7Joueurs: §e2/28", "", "§8§l» §aRejoindre la partie", "§f§m--§7»§f§m-----------------§7«§f§m--")).build(false), e -> {});
        setItem(22, new ItemBuilder(new CreateSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzkwZjYyZWM1ZmEyZTkzZTY3Y2YxZTAwZGI4YWY0YjQ3YWM3YWM3NjlhYTA5YTIwM2ExZjU3NWExMjcxMGIxMCJ9fX0=").toItemStack()).setDisplayName("             §f▪ §5§lONESHOT §f▪").setLoreWithList(Arrays.asList("§f§m--§7»§f§m-----------------§7«§f§m--", "  §c§nRègle du jeu §8§l»", "  §7● §fApparaissez avec un", "     §farc qui oneShot, et une", "     §fépée qui threeShot les", "     §fadversaires, afin d'être à", "     §fla tête du classement.", "", "§f➠ §7Développeur: §60hEliott", "§f➠ §7Version: §a1.8.8", "", "§f➠ §7Booster: Aucun", "§f➠ §7Joueurs: §e2/28", "", "§8§l» §aRejoindre la partie", "§f§m--§7»§f§m-----------------§7«§f§m--")).build(false), e -> {});
        setItem(31, new ItemBuilder(new CreateSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2FmNTk3NzZmMmYwMzQxMmM3YjU5NDdhNjNhMGNmMjgzZDUxZmU2NWFjNmRmN2YyZjg4MmUwODM0NDU2NWU5In19fQ==").toItemStack()).setDisplayName("               §f▪ §9§lRUSH §f▪").setLoreWithList(Arrays.asList("§f§m--§7»§f§m-----------------§7«§f§m--", "  §c§nRègle du jeu §8§l»", "  §7● §f2 équipes s'affrontent", "     §favec chacune une base ", "     §fqui contient un lit qu'il", "     §ffaut protéger afin de", "     §fde pouvoir réaparaître.", "", "§f➠ §7Développeur: §60hEliott", "§f➠ §7Version: §a1.8.8", "", "§f➠ §7Booster: Aucun", "§f➠ §7Joueurs: §e2/28", "", "§8§l» §aRejoindre la partie", "§f§m--§7»§f§m-----------------§7«§f§m--")).build(false), e -> {});
        setItem(21, new ItemBuilder(new CreateSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzhlOTkzNzU0NjU3MmI5YTRlMjM4YzljZmUyZDgzYjRiYjA5ZTljMTMxNjY3YTQ4MDQ5NWQ1OWNlYjUxNThmNSJ9fX0=").toItemStack()).setDisplayName("           §f▪ §e§lMADNESS §f▪").setLoreWithList(Arrays.asList("§f§m--§7»§f§m-----------------§7«§f§m--", "  §c§nRègle du jeu §8§l»", "  §7● §fApparraissez dans une", "     §fcarte, afin de vous stuffer", "     §fpour pouvoir combattre les", "     §fadversaires.", "", "§f➠ §7Développeur: §60hEliott", "§f➠ §7Version: §a1.8.8", "", "§f➠ §7Booster: Aucun", "§f➠ §7Joueurs: §e2/28", "", "§8§l» §aRejoindre la partie", "§f§m--§7»§f§m-----------------§7«§f§m--")).build(false), e -> {});
        setItem(32, new ItemBuilder(new CreateSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODQ4YTE5Y2RmNDJkNzQ4YjQxYjcyZmI0Mzc2YWUzZjYzYzExNjVkMmRjZTA2NTE3MzNkZjI2MzQ0NmM3N2JhNiJ9fX0=9").toItemStack()).setDisplayName("             §f▪ §b§lSKYRUSH §f▪").setLoreWithList(Arrays.asList("§f§m--§7»§f§m-----------------§7«§f§m--", "  §c§nRègle du jeu §8§l»", "  §7● §fApparaissez dans une", "     §fbase avec des TNT spéciales", "     §fuafin de vous propulser et", "     §fde tuer des gens pour", "     §fatteindre le top du", "     §fclassement.", "", "§f➠ §7Développeur: §60hEliott", "§f➠ §7Version: §a1.8.8", "", "§f➠ §7Booster: Aucun", "§f➠ §7Joueurs: §e2/28", "", "§8§l» §aRejoindre la partie", "§f§m--§7»§f§m-----------------§7«§f§m--")).build(false), e -> {});
        setItem(30, new ItemBuilder(new CreateSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDVmNDk5M2VmNTZmZjFiOWMyYjE2MjI1MWNjNTA1ZGYwNmIxYzFiZjdkNDk4MzY5OGFjZjU3YmE4Y2UxZmI1NCJ9fX0=").toItemStack()).setDisplayName("            §f▪ §6§lGUNGAMES §f▪").setLoreWithList(Arrays.asList("§f§m--§7»§f§m-----------------§7«§f§m--", "  §c§nRègle du jeu §8§l»", "  §7● §fApparaissez dans une", "     §fcarte avec une arme, et", "     §féliminez des gens avec cette", "     §fdernière pour changer d'arme.,", "     §fLe premier avec la 10ème", "     §farme gagne la partie.", "", "§f➠ §7Développeur: §60hEliott", "§f➠ §7Version: §a1.8.8", "", "§f➠ §7Booster: Aucun", "§f➠ §7Joueurs: §e2/28", "", "§8§l» §aRejoindre la partie", "§f§m--§7»§f§m-----------------§7«§f§m--")).build(false), e -> {});

        setItem(4, new ItemBuilder(new CreateSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmE5MDUzZDIxNjNkMGY1NjExNDVkMzNhNTEzMTQ1ZDRhYzFmOGE0NThiYWE3OTZiZTM4M2U3NTI1YTA1ZjQ1In19fQ").toItemStack()).setDisplayName("§8§l» §bServeurs Hosts").setLoreWithList(Arrays.asList("§7§oPermet d'avoir accès à la liste des","§7§ohosts","","§8§l» §eCliquez pour ouvrir le menu")).build(false), e -> {});
        setItem(51, new ItemBuilder(new CreateSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWM0OTcwZWE5MWFiMDZlY2U1OWQ0NWZjZTc2MDRkMjU1NDMxZjJlMDNhNzM3YjIyNjA4MmM0Y2NlMWFjYTFjNCJ9fX0=").toItemStack()).setDisplayName("§8§l» §bJump des dieux").setLoreWithList(Arrays.asList("§7§oPermet de se téléporter au jump", "§7§odes dieux.", "", "§8§l» §eCliquez pour se téléporter")).build(false), e -> {});
        setItem(47, new ItemBuilder(new CreateSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWNiN2MyMWNjNDNkYzE3Njc4ZWU2ZjE2NTkxZmZhYWIxZjYzN2MzN2Y0ZjZiYmQ4Y2VhNDk3NDUxZDc2ZGI2ZCJ9fX0=").toItemStack()).setDisplayName("§8§l» §aLobby").setLoreWithList(Arrays.asList("§7§oPermet de voir la liste des lobby", "§7§odisponibles, et de s'y connecter.", "", "§8§l» §eClique gauche pour aller au spawn", "§8§l» §eClique droit pour changer de hub")).build(false), e -> {});
        setItem(49, new ItemBuilder(Material.BARRIER).setDisplayName("§8§l» §cFermer").setLoreWithList(Arrays.asList("§7§oPermet de fermer le menu présent.", "", "§8§l» §eCliquez pour fermer le menu")).build(false), e -> {});
    }
}
